In [24]:
import torch
import torch.nn as nn


In [59]:
linear_layer = nn.Linear(16, 1, bias=False)
print (linear_layer.weight)

Parameter containing:
tensor([[0.4786]], requires_grad=True)


In [60]:
input_tensor = torch.randn(16, 16)
print (input_tensor)

tensor([[2.1823]])


In [61]:
output_tensor = linear_layer(input_tensor)
print (output_tensor)

tensor([[1.0445]], grad_fn=<MmBackward0>)
